#!/bin/bash
#
# /etc/init.d/register-service
 
case "$1" in
    start)
        echo "Start service...."
        source /opt/environment
        /usr/bin/java -jar /opt/register-1.0.0.jar &
        ;;
 
    stop)
        echo "Stop service..."
        pid=`pgrep -f register-1.0.0`
        if [ -z "$pid" ]
        then
            echo "Sytem wasn't started"
        else
            kill -9 "$pid"
        fi
        ;;
 
    restart)
        echo "Restart service..."
        # comando para reiniciar o serviço
        ;;
 
    *)
        echo "Operação inválida"
        ;;
esac
